// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace task1.Models
{
    public partial class Course
    {
        public Course()
        {
            Stud_Course = new HashSet<Stud_Course>();
        }

        [Key]
        public int Crs_Id { get; set; }
        [StringLength(50)]
        public string Crs_Name { get; set; }
        public int? Crs_Duration { get; set; }
        public int? Top_Id { get; set; }

        [InverseProperty("Crs_")]
        public virtual ICollection<Stud_Course> Stud_Course { get; set; }
    }
}