// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace task1.Models
{
    public partial class Student
    {
        public Student()
        {
            InverseSt_superNavigation = new HashSet<Student>();
            Stud_Course = new HashSet<Stud_Course>();
        }

        [Key]
        public int St_Id { get; set; }
        [StringLength(50)]
        public string St_Fname { get; set; }
        [StringLength(10)]
        public string St_Lname { get; set; }
        [StringLength(100)]
        public string St_Address { get; set; }
        public int? St_Age { get; set; }
        public int? Dept_Id { get; set; }
        public int? St_super { get; set; }

        [ForeignKey(nameof(St_super))]
        [InverseProperty(nameof(Student.InverseSt_superNavigation))]
        public virtual Student St_superNavigation { get; set; }
        [InverseProperty(nameof(Student.St_superNavigation))]
        public virtual ICollection<Student> InverseSt_superNavigation { get; set; }
        [InverseProperty("St_")]
        public virtual ICollection<Stud_Course> Stud_Course { get; set; }
    }
}