// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace task1.Models
{
    public partial class Stud_Course
    {
        [Key]
        public int Crs_Id { get; set; }
        [Key]
        public int St_Id { get; set; }
        public int? Grade { get; set; }

        [ForeignKey(nameof(Crs_Id))]
        [InverseProperty(nameof(Course.Stud_Course))]
        public virtual Course Crs_ { get; set; }
        [ForeignKey(nameof(St_Id))]
        [InverseProperty(nameof(Student.Stud_Course))]
        public virtual Student St_ { get; set; }
    }
}